name: Semantic release 

on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install 
      - name: Build app
        run: npm run build 
      - name: Semantic release
        env:
          GITHUB_TOKEN: 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
          NPM_TOKEN: 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
        run: npx semantic-release
